language: cpp

sudo: required

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update

install:
  - sudo apt-get install libgtest-dev python-dev g++-4.8
  - export GXX=g++-4.8
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libgtest* /usr/lib/
  - sudo pip install cpp-coveralls
  - cd "${TRAVIS_BUILD_DIR}"

compiler:
  - g++

script:
  - make test

after_success:
  - coveralls --gcov /usr/bin/gcov-4.8 --gcov-options '\-lp' --exclude test

